### ISSUE TITLE
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\mirza\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\python.exe', '-mvirtualenv', 'C:\\Users\\mirza\\.cache\\pre-commit\\repokr1qkvgd\\py_env-python3.10') return code: 1

### ISSUE THREAD

**Issue by Umekko** [SENATOROVAI/pre-commit#15]
### Checklist

- [X] I added a descriptive title.
- [X] I searched through [existing issues](https://t.me/c/1937296927/3602/25534) and couldn't find a solution or duplicate issue.
- [X] I searched on the web (e.g. Google) or [chatGPT](https://t.me/c/1937296927/2415/23729) and didn't find any helpful information.

### Attach a screenshot and write what did you do to fix the problem?

![image](https://github.com/user-attachments/assets/ce5ffdc8-9731-4654-9e94-f1ae447e13c6)

Actually nothing

### Error from the terminal / Code

An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\mirza\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\python.exe', '-mvirtualenv', 'C:\\Users\\mirza\\.cache\\pre-commit\\repokr1qkvgd\\py_env-python3.10')
return code: 1
stdout:
    RuntimeError: failed to build image setuptools because:
    Traceback (most recent call last):
      File "C:\Users\mirza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\virtualenv\seed\embed\via_app_data\via_app_data.py", line 57, in _install
        installer.install(creator.interpreter.version_info)
      File "C:\Users\mirza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\virtualenv\seed\embed\via_app_data\pip_install\base.py", line 33, in install
        self._uninstall_previous_version()
      File "C:\Users\mirza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\virtualenv\seed\embed\via_app_data\pip_install\base.py", line 144, in _uninstall_previous_version
        dist_name = self._dist_info.stem.split("-")[0]
      File "C:\Users\mirza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\virtualenv\seed\embed\via_app_data\pip_install\base.py", line 110, in _dist_info
        raise RuntimeError(msg)  # pragma: no cover
    RuntimeError: no .dist-info at C:\Users\mirza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.10\image\1\CopyPipInstall\setuptools-72.1.0-py3-none-any, has distutils-precedence.pth, pkg_resources, _distutils_hack
stderr: (none)
Check the log at C:\Users\mirza\.cache\pre-commit\pre-commit.log

### Expected behavior

Commit to github

### Actual behavior

Failed to commit new changes

[pre-commit.log](https://github.com/user-attachments/files/17544738/pre-commit.log)

**Comment by ruslansenatorov** [comment]
python -m pip install --upgrade pip setuptools

**Comment by ruslansenatorov** [comment]
pip install --upgrade pre-commit

**Comment by Umekko** [comment]
> pip install --upgrade pre-commit

This command fixed my problem, pre-commit was old version
